concurrent = 1

[session_server]
  session_timeout = 18000

[[runners]]
  name = "___YOUR_RUNNER_NAME___"
  url = "https://___YOUR_RUNNER_domain___/"
  token = "___YOUR_RUNNER_TOKEN___"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "mr-runner"
    Shared = false
    [runners.cache.s3]
    ServerAddress = "http://minio:9000"
    AccessKey = "minioadmin"
    SecretKey = "minioadmin"
    BucketName = "___YOUR_BUCKET_NAME___"
    BucketLocation = "eu-west-1"
    Insecure = true
  [runners.docker]
    tls_verify = false
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
